# Site settings
title: Dayana Duarte Estética
description: "Servicios de belleza por profesional certificada."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/DDE_logo.png

# Hero (BGHeader)
hero: 
    hero_img: bgheader.jpg
    hero_title: Dayana Duarte Estética
    hero_description: Profesional de la belleza.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 916 50 44 56
    movil: 672 06 69 99
    email: citas@dayanaduarteestetica.com
    address: Centro Comercial Cuesta Blanca local 10 (Urban Nails), 28100, Alcobendas, Madrid

# Opening hours
monday_friday: 10:00 – 19:00
saturday: 10:00 – 14:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 15
    address: 28108, Calle de Cuesta Blanca, 2, 28108 Alcobendas, Madrid
    address_details: uploads/mapaUrbanNails.png

# Social settings
facebook: https://www.facebook.com/dayanekenneth
instagram: https://www.instagram.com/dayanaduarteestetica/
#  twitter: http://twitter.com
# youtube: http://youtube.com
# skype: 
feed: yes

# Footer
copyright: © 2020 Dayana Duarte Estética - Derechos Reservados

# Build settings
markdown: kramdown

plugins:
- jekyll-menus

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    LICENSE.md,
    README.md
]

# Theme Settings
analytics: 
google_verification:

